### ISSUE TITLE
a advise when run grapy.py

### ISSUE THREAD

**Issue by GinSoda** [fyubang/Joint-BERT-KBQA#2]
32G memory may cause MemoryError. Close useless process first or change to a larger memory

**Comment by GinSoda** [comment]
如果实验室内存资源比较少，可以使用云主机（比如极客云）

**Comment by fyubang** [comment]
> 如果实验室内存资源比较少，可以使用云主机（比如极客云）

或者建议用elastic search代替直接把整个图读进内存。
