### ISSUE TITLE
about bert package

### ISSUE THREAD

**Issue by GinSoda** [fyubang/Joint-BERT-KBQA#3]
这个bert是从huggingface的transformers(早期版本)复制下来的，我还以为是google官方那个bert库😂

**Comment by GinSoda** [comment]
如果把bert库改成最新的transformers库，注意以下代码调整
transformers代码版本变化
```
[1] BertModel.forward()中的output_all_encoded_layer参数改成了BertEncoder.__init__()中的
output_hidden_states，具体定义在PretrainedConfig class中
[2] BertModel.__init__()参数初始化代码
self.apply(self.init_bert_weights) -> self.init_weights()
[3] BertAdam class拆分成了 AdamW class 和WarmupLinearSchedule class
[4] WarmupLinearSchedule class 改成了get_linear_schedule_with_warmup()函数，返回的是
torch.optim.lr_scheduler.LambdaLR class
[5] BertModel.forward()位置形参顺序调整
BertModel.forward(self, input_ids=None, token_type_ids=None, attention_mask=None)
-> BertModel.forward(self, input_ids=None, attention_mask=None, token_type_ids=None)
```

**Comment by fyubang** [comment]
> 如果把bert库改成最新的transformers库，注意以下代码调整
> transformers代码版本变化
> 
> ```
> [1] BertModel.forward()中的output_all_encoded_layer参数改成了BertEncoder.__init__()中的
> output_hidden_states，具体定义在PretrainedConfig class中
> [2] BertModel.__init__()参数初始化代码
> self.apply(self.init_bert_weights) -> self.init_weights()
> [3] BertAdam class拆分成了 AdamW class 和WarmupLinearSchedule class
> [4] WarmupLinearSchedule class 改成了get_linear_schedule_with_warmup()函数，返回的是
> torch.optim.lr_scheduler.LambdaLR class
> [5] BertModel.forward()位置形参顺序调整
> BertModel.forward(self, input_ids=None, token_type_ids=None, attention_mask=None)
> -> BertModel.forward(self, input_ids=None, attention_mask=None, token_type_ids=None)
> ```

感谢~项目里的bert代码是Huggingface早期的，因为tokenization部分做了一点小修改(便于从tokens恢复到原句)，所以一直用着这一套。
