### ISSUE TITLE
端对端

### ISSUE THREAD

**Issue by OKtang** [fyubang/Joint-BERT-KBQA#5]
你好，
由于对端对端一直理解的不清楚，想请问你是怎么理解端对端的呢？端对端的基本要求是什么呢？以及你的这个方法为什么可以称为端对端的方法呢？还有请问你实体链接步骤是怎么处理的呢？

**Comment by fyubang** [comment]
> 你好，
> 由于对端对端一直理解的不清楚，想请问你是怎么理解端对端的呢？端对端的基本要求是什么呢？以及你的这个方法为什么可以称为端对端的方法呢？还有请问你实体链接步骤是怎么处理的呢？

很多时候，解决一个任务需要很多个步骤。比如这里的KBQA，如果在训练的时候，将NER和RE分开训练，NER的最优解不能保证RE的问题达到最优。端到端的系统同步优化两个任务。
实体链接就是简单的Name Dictionary Based Methods，具体的你可以看源码。
